name: helper_options
description: A library to use the option of any object.
version: 0.1.0+4
homepage: https://github.com/muhammadmateen027/optionals

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: ">=1.24.0-6.0.pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
